# Arquivo: .nixpacks.toml

[phases.setup]
nixpkgs = ["php82", "php82Extensions.mysqli"]

[phases.install]
cmds = []

[phases.build]
cmds = []

[phases.start]
cmds = [
  "php -S 0.0.0.0:3000 index.php"
]

[start]
cmd = "php -S 0.0.0.0:3000 index.php"
